const products={milk:{name:'Pure cow milk',rate:70,unit:'litre',image:'gallery4.png'},curd:{name:'Fresh cow curd',rate:120,unit:'kg',image:'gallery2.png'},ghee:{name:'Pure cow ghee',rate:1400,unit:'kg',image:'gallery3.jpg'}};
const $=id=>document.getElementById(id),product=$('product'),quantity=$('quantity');
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);
function validQty(){const value=Number(quantity.value);return Number.isFinite(value)&&value>=.5?Math.round(value*2)/2:.5}
function updateOrder(){const item=products[product.value],qty=validQty(),total=item.rate*qty;quantity.value=qty;$('rate').textContent=`₹${item.rate.toLocaleString('en-IN')} / ${item.unit}`;$('total').textContent=money(total);$('productImage').src=item.image;$('productImage').alt=item.name;$('summaryName').textContent=item.name;$('summaryQty').textContent=`${qty} ${item.unit}${qty===1?'':'s'}`;$('summaryRate').textContent=`₹${item.rate.toLocaleString('en-IN')} / ${item.unit}`;$('summaryTotal').textContent=money(total)}
const requested=new URLSearchParams(location.search).get('product');if(products[requested])product.value=requested;product.addEventListener('change',updateOrder);quantity.addEventListener('input',()=>{if(quantity.value!=='')updateOrder()});quantity.addEventListener('change',updateOrder);$('minus').addEventListener('click',()=>{quantity.value=Math.max(.5,validQty()-.5);updateOrder()});$('plus').addEventListener('click',()=>{quantity.value=validQty()+.5;updateOrder()});
$('mobile').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,10));
$('orderForm').addEventListener('submit',event=>{event.preventDefault();const name=$('customerName').value.trim(),mobile=$('mobile').value.trim(),address=$('address').value.trim(),note=$('note').value.trim(),item=products[product.value],qty=validQty(),total=item.rate*qty,error=$('formError');if(!name||!/^[0-9]{10}$/.test(mobile)||!address){error.textContent='Please enter your name, a valid 10-digit mobile number and delivery address.';error.classList.add('show');return}error.classList.remove('show');const lines=['Hello Mithila Parivar Dairy Farm,','I would like to place an order.','',`Customer: ${name}`,`Mobile: ${mobile}`,`Product: ${item.name}`,`Quantity: ${qty} ${item.unit}${qty===1?'':'s'}`,`Rate: ₹${item.rate.toLocaleString('en-IN')} per ${item.unit}`,`Total amount: ${money(total)}`,`Delivery address: ${address}`];if(note)lines.push(`Additional note: ${note}`);lines.push('','Please confirm availability and delivery.');window.location.href=`https://wa.me/918298867478?text=${encodeURIComponent(lines.join('\n'))}`});
$('year').textContent=new Date().getFullYear();updateOrder();

